### ISSUE TITLE
Issue With Installation

### ISSUE THREAD

**Issue by DK7GitHub** [mrcsparker/nifi-edireader-bundle#9]
We are having issues getting the NIFI EDIReader Processor installed.  Can you please assist us with installation of this plugin.  We have NIFI up and running we just need this piece to help us parse information.

We:
Git clone,
Cd edireader,
Mvn install 

Then we go to cd nifi-edireader-processor
We mvn package -----Then we get an error.  

I have attached a word doc with our error after running mvn package.

Any help resolving this would be much appreciated.

The error at the bottom states:

[ERROR] Failed to execute goal org.codehaus.mojo:buildnumber-maven-plugin:1.4:create (default) on project nifi-edireader-bundle: Cannot get the revision information from the scm repository :
[ERROR] Exception while executing SCM command.: Error while executing command. Error while executing process. Cannot run program "git" (in directory "c:\edireader\nifi-edireader-processor"): CreateProcess error=2, The system cannot find the file specified
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

Thanks very much for your help.

[GitHub_Error.docx](https://github.com/mrcsparker/nifi-edireader-bundle/files/2442485/GitHub_Error.docx)

**Comment by mrcsparker** [comment]
It looks like it can't find git

**Comment by mrcsparker** [comment]
Since there is no response I am closing this ticket
